diff --git a//dev/null b/.hadolint.yaml
index 0000000000000000000000000000000000000000..fe292a86e4ebaf06c4455856238c68d09e44a5c1 100644
--- a//dev/null
+++ b/.hadolint.yaml
@@ -0,0 +1,7 @@
+---
+ignored:
+  - DL3006 # Always tag the version of an image explicitly
+  - DL3008 # Pin apk add versions (often impractical for HA base)
+  - DL3018 # Pin apk versions
+  - DL3059 # Multiple consecutive RUNs (allowed for readability)
+failure-threshold: warning
