diff --git a//dev/null b/.yamllint.yaml
index 0000000000000000000000000000000000000000..dfb9ed2d35f7f90e13ed37ce05bbc6a981035239 100644
--- a//dev/null
+++ b/.yamllint.yaml
@@ -0,0 +1,11 @@
+---
+extends: default
+rules:
+  line-length:
+    max: 160
+    level: warning
+  truthy: disable
+  comments:
+    min-spaces-from-content: 1
+  indentation:
+    indent-sequences: consistent
