---
name: "Chrony Secure Time"
slug: "chrony-nts"
description: >-
  Chrony with Network Time Security upstreams. Acts as a secure client or a
  gateway that serves plain NTP to your LAN.
version: "2.0.0-beta.5"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
privileged:
  - SYS_TIME
apparmor: true
init: false

options:
  mode: secure_client
  nts_upstreams:
    - time.cloudflare.com
    - nts.time.nl
    - nts.netnod.se
  set_system_clock: true
  allow_ipv4: []
  allow_ipv6: []
  bootstrap_strategy: persistent_then_initstepslew
  extra_config: ""

schema:
  mode: list(secure_client|secure_gateway)
  nts_upstreams:
    - str
  set_system_clock: bool
  allow_ipv4:
    - str
  allow_ipv6:
    - str
  bootstrap_strategy: list(persistent_then_initstepslew|persistent_only|initstepslew|oneshot|none)  # yamllint disable-line rule:line-length
  extra_config: str?
