#!/command/with-contenv bashio
set -Eeuo pipefail

CONF="/etc/chrony/chrony.conf"
DATA_DIR="/data/chrony"

mkdir -p "$DATA_DIR"
chmod 0700 "$DATA_DIR" || true

MODE="$(bashio::config 'mode')"
POOL="$(bashio::config 'ntp_pool')"
ALLOW_RAW="$(bashio::config 'allow' | tr ',' ' ')"
USE_NTS="$(bashio::config 'use_nts')"
LOCAL_FALLBACK="$(bashio::config 'local_fallback')"
EXTRA_CONFIG="$(bashio::config 'extra_config' || true)"

# Read server list (array)
mapfile -t SERVERS < <(bashio::config 'ntp_server[]' 2>/dev/null || true)

# Build config
{
  echo "# Generated by Home Assistant Chrony add-on"
  echo "driftfile ${DATA_DIR}/chrony.drift"
  echo "makestep 1.0 3"
  echo "rtcsync"

  # ACLs
  for net in ${ALLOW_RAW}; do
    [ -n "$net" ] && echo "allow ${net}"
  done

  # Sources
  if [ "${MODE}" = "pool" ]; then
    if [ -n "${POOL:-}" ]; then
      if bashio::var.true "${USE_NTS}"; then
        echo "pool ${POOL} iburst nts"
      else
        echo "pool ${POOL} iburst"
      fi
    fi
  else
    for host in "${SERVERS[@]}"; do
      [ -z "$host" ] && continue
      if bashio::var.true "${USE_NTS}"; then
        echo "server ${host} iburst nts"
      else
        echo "server ${host} iburst"
      fi
    done
  fi

  # Persist NTS cookies if enabled
  if bashio::var.true "${USE_NTS}"; then
    echo "ntsdumpdir ${DATA_DIR}"
  fi

  # Optional local fallback (off by default)
  if bashio::var.true "${LOCAL_FALLBACK}"; then
    echo "local stratum 10"
  fi

  # Advanced user-provided lines (appended verbatim)
  if [ -n "${EXTRA_CONFIG:-}" ]; then
    echo
    echo "# --- extra_config (verbatim) ---"
    echo "${EXTRA_CONFIG}"
  fi
} > "${CONF}"

bashio::log.info "chrony.conf rendered at ${CONF}"
